name: fiotestbot

on:
  workflow_dispatch:
# schedule:
#   - cron: "* /15 * * *" # every 15 minutes

permissions:
  contents: write

jobs:
  query:
    runs-on: ubuntu-latest

    outputs:
      msg_ids: ${{ steps.msg_ids.outputs.msg_ids }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: git setup
      run: |
        git config --global user.email "fiotestbot@users.noreply.github.com"
        git config --global user.name "fiotestbot"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3-bs4 python3-github

    - name: Run query to collect message IDs
      id: msg_ids
      run: |
        MSGIDS=$(python3 query.py -s --since 20240915... | jq --raw-input . | jq --slurp .)
        echo $MSGIDS
        echo msg_ids=$MSGIDS >> $GITHUB_OUTPUT
#
# TODO get rid of since above when deploying this for real
#

    - name: update repository with new message IDs
      if: ${{ steps.msg_ids.outputs.msg_ids != '[]' }}
      run: |
        git commit -m "update message IDs"
        git push

    - name: check for complete GitHub Actions
      run: |
        python3 query.py --notify

  runtests:
    needs: query
    runs-on: ubuntu-latest
    if: ${{ needs.query.outputs.msg_ids != '[]' }}

    strategy:
      matrix:
        msg_id: ${{fromJson(needs.query.outputs.msg_ids)}}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        repository: axboe/fio
        ref: aa665180df233e10ed9a616702d881448d81651b
        fetch-depth: 0
        ssh-key: ${{ secrets.SSH_KEY }}
#
# TODO change ref to master when running this for real
#

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install b4

    - name: git setup
      run: |
        git config --global user.email "fiotestbot@users.noreply.github.com"
        git config --global user.name "fiotestbot"
        git remote set-url origin git@github.com:fiotestbot/fio.git
#
# Create token: Settings->Developer settings->Personal access tokens->Generate new token
# Set secret: Settings->Secrets and variables->Actions->New repository secret
#

    - name: Create a new branch and push it
      run: |
        echo ${{ matrix.msg_id }}
        git checkout -b test-${{ matrix.msg_id }}
        b4 am -3 -o - "${{ matrix.msg_id }}" | git am --whitespace=fix
        git push origin test-${{ matrix.msg_id }}
